version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: backend/.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dsm_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
